### ISSUE TITLE
--help

### ISSUE THREAD

**Issue by d33pcode** [streambinder/spotify-dl#1]
Please dispay some usage or people will `go` mad.

Also, think about a more instinctive `-f/--folder` option instead of `--music`.

**Comment by streambinder** [comment]
`help` option already exists:
```
$ ./bin/spotify-dl -help/--help
Usage of ./bin/spotify-dl:
  -music string
    	Folder to sync with music. (default "~/Music")
```
Anyway, accepted switching from `-music` to `-folder` flag name.
